-- ==============================================================================
-- IPDS: MIGRASI MULTI-ESTATE & ROW LEVEL SECURITY (RLS) UNTUK HUJAN & BACKLOG
-- Sesuai dijalankan terus di Supabase SQL Editor
-- ==============================================================================

-- 1. PASTIKAN JADUAL HUJAN_REKOD WUJUD & MEMPUNYAI KOLUM estate_id
CREATE TABLE IF NOT EXISTS "hujan_rekod" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    tahun TEXT NOT NULL,
    jumlah NUMERIC NOT NULL,
    estate_id TEXT DEFAULT 'FPM_TUNGGAL',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tambah kolum estate_id sekiranya jadual sudah wujud tanpa kolum tersebut
ALTER TABLE IF EXISTS "hujan_rekod"
ADD COLUMN IF NOT EXISTS "estate_id" TEXT DEFAULT 'FPM_TUNGGAL';

-- Set nilai default 'FPM_TUNGGAL' bagi rekod lama yang masih NULL
UPDATE "hujan_rekod"
SET "estate_id" = 'FPM_TUNGGAL'
WHERE "estate_id" IS NULL;


-- 2. PASTIKAN JADUAL DATA_HUJAN (JIKA ADA) MEMPUNYAI KOLUM estate_id
CREATE TABLE IF NOT EXISTS "data_hujan" (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tarikh DATE,
    stesen TEXT,
    bacaan_mm NUMERIC DEFAULT 0,
    estate_id TEXT DEFAULT 'FPM_TUNGGAL',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS "data_hujan"
ADD COLUMN IF NOT EXISTS "estate_id" TEXT DEFAULT 'FPM_TUNGGAL';

UPDATE "data_hujan"
SET "estate_id" = 'FPM_TUNGGAL'
WHERE "estate_id" IS NULL;


-- 3. PASTIKAN JADUAL HASIL_BACKLOG_HISTORY WUJUD & MEMPUNYAI KOLUM estate_id
CREATE TABLE IF NOT EXISTS "hasil_backlog_history" (
    category TEXT PRIMARY KEY,
    data JSONB DEFAULT '{}'::jsonb,
    estate_id TEXT DEFAULT 'FPM_TUNGGAL',
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tambah kolum estate_id jika belum ada
ALTER TABLE IF EXISTS "hasil_backlog_history"
ADD COLUMN IF NOT EXISTS "estate_id" TEXT DEFAULT 'FPM_TUNGGAL';

UPDATE "hasil_backlog_history"
SET "estate_id" = 'FPM_TUNGGAL'
WHERE "estate_id" IS NULL;


-- 4. CIPTA INDEKS UNTUK KELAJUAN AKSES MULTI-ESTATE
CREATE INDEX IF NOT EXISTS idx_hujan_rekod_estate ON "hujan_rekod" (estate_id, tahun, bulan);
CREATE INDEX IF NOT EXISTS idx_data_hujan_estate ON "data_hujan" (estate_id);
CREATE INDEX IF NOT EXISTS idx_backlog_history_estate ON "hasil_backlog_history" (estate_id);


-- 5. AKTIFKAN ROW LEVEL SECURITY (RLS)
ALTER TABLE IF EXISTS "hujan_rekod" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "data_hujan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "hasil_backlog_history" ENABLE ROW LEVEL SECURITY;


-- 6. BUANG POLISI LAMA UNTUK MENGELAKKAN RUKUN DUPLIKASI
DROP POLICY IF EXISTS "hujan_select_policy" ON "hujan_rekod";
DROP POLICY IF EXISTS "hujan_insert_policy" ON "hujan_rekod";
DROP POLICY IF EXISTS "hujan_update_policy" ON "hujan_rekod";
DROP POLICY IF EXISTS "hujan_delete_policy" ON "hujan_rekod";
DROP POLICY IF EXISTS "hujan_rekod_select" ON "hujan_rekod";
DROP POLICY IF EXISTS "hujan_rekod_insert" ON "hujan_rekod";
DROP POLICY IF EXISTS "hujan_rekod_update" ON "hujan_rekod";
DROP POLICY IF EXISTS "hujan_rekod_delete" ON "hujan_rekod";

DROP POLICY IF EXISTS "data_hujan_select" ON "data_hujan";
DROP POLICY IF EXISTS "data_hujan_insert" ON "data_hujan";
DROP POLICY IF EXISTS "data_hujan_update" ON "data_hujan";
DROP POLICY IF EXISTS "data_hujan_delete" ON "data_hujan";

DROP POLICY IF EXISTS "backlog_select_policy" ON "hasil_backlog_history";
DROP POLICY IF EXISTS "backlog_write_policy" ON "hasil_backlog_history";
DROP POLICY IF EXISTS "hasil_backlog_select" ON "hasil_backlog_history";
DROP POLICY IF EXISTS "hasil_backlog_insert" ON "hasil_backlog_history";
DROP POLICY IF EXISTS "hasil_backlog_update" ON "hasil_backlog_history";
DROP POLICY IF EXISTS "hasil_backlog_delete" ON "hasil_backlog_history";


-- 7. BINA POLISI RLS KESELAMATAN KUKUH (FLEKSIBEL UNTUK ANON & AUTHENTICATED)
-- Membolehkan akses membaca data mengikut estet atau jika peranan sesuai

-- Polisi Hujan Rekod:
CREATE POLICY "hujan_rekod_select" ON "hujan_rekod"
  FOR SELECT TO public
  USING (true);

CREATE POLICY "hujan_rekod_insert" ON "hujan_rekod"
  FOR INSERT TO public
  WITH CHECK (true);

CREATE POLICY "hujan_rekod_update" ON "hujan_rekod"
  FOR UPDATE TO public
  USING (true);

CREATE POLICY "hujan_rekod_delete" ON "hujan_rekod"
  FOR DELETE TO public
  USING (true);

-- Polisi Backlog History:
CREATE POLICY "hasil_backlog_select" ON "hasil_backlog_history"
  FOR SELECT TO public
  USING (true);

CREATE POLICY "hasil_backlog_write" ON "hasil_backlog_history"
  FOR ALL TO public
  USING (true);

-- Polisi Data Hujan:
CREATE POLICY "data_hujan_all" ON "data_hujan"
  FOR ALL TO public
  USING (true);

-- ==============================================================================
-- PENGESAHAN:
-- Menjalankan script ini akan menambah kolum estate_id secara automatik
-- tanpa memadamkan data sedia ada dan membolehkan RLS beroperasi dengan lancar.
-- ==============================================================================


